name: Deploy to Azure
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to Docker
        uses: azure/docker-login@v1
        with:
          login-server: index.docker.io
          username: ${{ secrets.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_PASSWORD }}

      - name: Login to Azure
        uses: azure/docker-login@v1
        with:
          login-server: healthbotregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}


      - name: Deploy
        run: |
          docker build -t healthbotregistry.azurecr.io/healthbot:latest .
          docker push healthbotregistry.azurecr.io/healthbot

