name: Safety check
on:
  push:
    branches:
      - main
      
jobs: 
  safety-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: securityCheck       
        uses: aufdenpunkt/python-safety-check@master